### PR TITLE
Changes attribution close button label. Fixes #1075

### LINKED ISSUE #1075: Accessibility issue: insufficient label on attribution box close button
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
close button for attribution box

### Issue description
The accessible label for the close button for the attribution box is "close". It is hard for a screenreader user to assess what this button is meant to close. 
Even having the text above and below the button read out by the screenreader will not make it 100 percent obvious what the button closes (especially as the button appears to be positioned between the heading of the box and its content).

### Steps to reproduce
To observe what a screenreader user experiences:
1. activate a screenreader
2. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
3. navigate to the attribution box by tabbing and listen to what is announced
4. attempt to find out more about the close button by further navigating using the keyboard and screenreader

### Expected behaviour
Button should be announced in a way that a non-sighted user would understand its context and purpose.

### Possible fix
Change accessible label to something along the lines of "close attribution box"

### WCAG criterion
2.4.4 Link Purpose (In Context) (Level A)

### Related code

```html
<button type="button" class="close" aria-label="Close"> <span aria-hidden="true">×</span> </button>
```

### PR DESCRIPTION
**Pull request by LlGC-mag**
Fixes #1075 

Supersedes #1160 

Applies option 1 from https://github.com/UniversalViewer/universalviewer/pull/1160#pullrequestreview-2388177647

@demiankatz I think this is what you described in option 1 but this is my first typescript project so please excuse any misunderstandings!

### CODE REVIEW

**Review by demiankatz — APPROVED** [review]
Thanks, @LlGC-mag, this is exactly what I had in mind, and it seems to be working perfectly. I appreciate you going the extra mile. :-)

**Comment by demiankatz** [comment]
(I'll wait for one more tester to confirm before hitting merge, just to be on the safe side).

**Comment by LanieOkorodudu** [comment]
@demiankatz. I've reviewed this and can confirm the fix when comparing it with the dev branch. The only remaining step is to verify it using a screen reader. I’m currently awaiting approval from our service desk to download the NVDA screen reader so I can complete this testing.

**Review by LanieOkorodudu — COMMENTED** [review]
@LlGC-mag @demiankatz , I’ve tested this fix with the NVDA screen reader, and I can confirm that the label correctly announces 'attribution close' as expected. Thank you @LlGC-mag

**Pull request merged**
