### PR TITLE
Link to settings dialog from warning message.

### PR DESCRIPTION
**Pull request by demiankatz**
This is a follow-up to #71, which adjusts the wording to be more consistent with the settings dialog box and also allows direct access to those settings. Perhaps a more fluid workflow could be devised, but this seems like the easiest approach without having to make larger-scale changes.

### CODE REVIEW

**Comment by demiankatz** [comment]
Probably goes without saying, but Welsh translations are best guesses!

**Comment by LlGC-szw** [comment]
Let us know if you need the Welsh translations corrected!

**Comment by demiankatz** [comment]
Help with the Welsh would definitely be appreciated -- but I'll let @edsilv comment on the best workflow to make that happen.

**Comment by LlGC-szw** [comment]
We could use our transifex account @edsilv , but let me know.

**Comment by demiankatz** [comment]
Ed previously mentioned Transifex to me, so I suspect this is well in hand. Thanks!

**Comment by edsilv** [comment]
I've updated your transifex account Sara. There are now a few new strings
to be translated.

**Comment by LlGC-szw** [comment]
Thanks Ed, I'll get this done today if I can.

**Pull request merged**
