### PR TITLE
Add focus highlight to gallery control buttons

### LINKED ISSUE #1080: Accessibility issue: insufficient focus highlight on gallery controls
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
gallery controls

### Issue description
Inside the gallery view (where all thumbnails are visible), the plus and minus buttons have insufficient focus highlight. They change colour from one shade of grey to another which is barely perceivable even without a visual impairment. The slider also receives focus and user can interact with it and it has no focus highlight at all.

### Steps to reproduce
1. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
2. tab to the gallery button in the top right corner and activate
3. tab to the buttons that control the gallery view (plus, minus, and slider) 
4. observe how their appearance changes (or not) when focus is on each element

### Expected behaviour
A clearly visible focus highlight that contrasts at least 3:1 with the initial state of the button as well as the background.

### Possible fix
Add the same focus frame that is applied to other elements or change the button colour to something radically different. 2.4.7 is very vague in what it considers a visible focus indicator but generally visibility is defined as a contrast of at least 3:1 in other criteria.

### WCAG criterion
[2.4.7 Focus Visible (Level AA)](https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html) 

### Related code (example)

```html
<div title="Zoom In" tabindex="0" class="zoomIn viewportNavButton" style="background: none transparent; border: none; margin: 0px; padding: 0px; position: relative; touch-action: none; display: inline-block;"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Zoom in" style="background: none transparent; border: none; margin: 0px; padding: 0px; position: static;"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Zoom in" style="background: none transparent; border: none; margin: 0px; padding: 0px; position: absolute; top: 0px; left: 0px; opacity: 0;"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Zoom in" style="background: none transparent; border: none; margin: 0px; padding: 0px; position: absolute; top: 0px; left: 0px; visibility: hidden;"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Zoom in" style="background: none transparent; border: none; margin: 0px; padding: 0px; position: absolute; top: 0px; left: 0px; visibility: hidden;"></div>
```

### Other information
My general advice is to review the focus highlight that is used across the viewer. It is not a bad idea to use [Criterion 2.4.13 Focus Appearance](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html) as a guidance. Although it is a bit complicated and an AAA requirement, it does provide excellent guidance what to aim for: a sufficiently large focus highlight that contasts with the highlighted element, its background, and the initial state of the element.

### PR DESCRIPTION
**Pull request by Saira-A**
Fixes #1080

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @Saira-A, this is definitely an improvement... but I wonder if something similar should also be applied to the range slider itself, as its focus still seems a bit hard to see.

Also, speaking of the slider, is it just me, or is the slider itself stretched out and overlapping the buttons in a weird way? It looks wrong to me in Firefox, at least. (And that's not a new problem -- just wondering if we can clean this all up while we're working on it anyway).

Happy to help fiddle with styles on my end if I can be of any help, though it's not my forte. ;-)

**Comment by Saira-A** [comment]
> Thanks, @Saira-A, this is definitely an improvement... but I wonder if something similar should also be applied to the range slider itself, as its focus still seems a bit hard to see.
> 
> Also, speaking of the slider, is it just me, or is the slider itself stretched out and overlapping the buttons in a weird way? It looks wrong to me in Firefox, at least. (And that's not a new problem -- just wondering if we can clean this all up while we're working on it anyway).
> 
> Happy to help fiddle with styles on my end if I can be of any help, though it's not my forte. ;-)

The slider looks ok to me, in Chrome at least. I kept the slider focus highlight the same as the buttons for consistency but I agree it's too subtle. Here's how it looks if I change the border to 2px, solid and double: 
Screenshot 2024-10-25 at 16 25 45
Screenshot 2024-10-25 at 16 27 06

**Comment by demiankatz** [comment]
Interesting! This looks fine in Chrome for me as well, but Firefox makes a mess of things:

image

Should we try to fix that before merging this, or would you rather treat that as a separate issue?

**Comment by Saira-A** [comment]
> Interesting! This looks fine in Chrome for me as well, but Firefox makes a mess of things:
> 
> image
> 
> Should we try to fix that before merging this, or would you rather treat that as a separate issue?

I just tested it on Safari as well and it looks fine but the focus highlight completely skips the one-up/two-up/gallery icons in the header - maybe we could do some cross-browser testing and then open up relevant issues?
I'll adjust this one so it can be merged at least - do you have a preference between the solid and the double border?

**Comment by demiankatz** [comment]
> I just tested it on Safari as well and it looks fine but the focus highlight completely skips the one-up/two-up/gallery icons in the header - maybe we could do some cross-browser testing and then open up relevant issues? I'll adjust this one so it can be merged at least - do you have a preference between the solid and the double border?

Yes, I think it's a good idea to test for cross-browser inconsistencies, and it's definitely worth opening an issue about the gallery icon issue if it is still a problem after we upgrade the gallery component. (There are some pending fixes in the upstream component that need to be released and integrated here, though I'm not sure if they'll have any impact on this issue).

I don't have a strong preference between the solid and double border. Based on the screen shots above, it looks like the double border may have better contrast, so perhaps that's the best option -- but I wouldn't fight against the solid option if you prefer it.

**Comment by demiankatz** [comment]
@Saira-A, the latest commit makes the focus look right in Firefox, but there's still a problem with the actual range control overflowing in weird ways. It appears that somewhere there is a style that is applying a 100px width to the range input, and for some reason, that's not scaling down the actual bar. If I go into inspector and take away the width style, then the range grows significantly and the weird overlapping bar goes away. I'm not sure where this is coming from or why it's behaving like this. Any ideas? Should we merge this as-is to fix the focus problem and open a separate issue or PR to address the bar width issue?

**Comment by Saira-A** [comment]
> @Saira-A, the latest commit makes the focus look right in Firefox, but there's still a problem with the actual range control overflowing in weird ways. It appears that somewhere there is a style that is applying a 100px width to the range input, and for some reason, that's not scaling down the actual bar. If I go into inspector and take away the width style, then the range grows significantly and the weird overlapping bar goes away. I'm not sure where this is coming from or why it's behaving like this. Any ideas? Should we merge this as-is to fix the focus problem and open a separate issue or PR to address the bar width issue?

I've had a brief look and I'm not sure how to make the bar itself smaller but adding this to the .less file at least fixes the overlap without affecting other browsers although now it's quite long:
`@-moz-document url-prefix() {
  .iiif-gallery-component .header input[type="range"] {
    margin-top: 7px;
    width: 300px;
  }
}`

Screenshot 2024-10-29 at 10 12 07

I could add that as a temporary fix and then open a separate issue to investigate properly?

**Comment by demiankatz** [comment]
@Saira-A, does using `width: auto` instead of `width: 300px` make any difference? If both yield the same result, then the version without the hard-coded number might be more reliable in the long term.

As far as strategy, since the rest of this PR doesn't depend on this fix, how would you feel about merging this as-is and then opening a separate PR to adjust the width problem? I'm happy to merge if that sounds good to you -- and then we could discuss potential improvements to the fix in the follow-up PR.

**Comment by Saira-A** [comment]
> @Saira-A, does using `width: auto` instead of `width: 300px` make any difference? If both yield the same result, then the version without the hard-coded number might be more reliable in the long term.
> 
> As far as strategy, since the rest of this PR doesn't depend on this fix, how would you feel about merging this as-is and then opening a separate PR to adjust the width problem? I'm happy to merge if that sounds good to you -- and then we could discuss potential improvements to the fix in the follow-up PR.

That brings back the overlap :( 
Screenshot 2024-10-29 at 10 37 50

That's fine with me - could it possibly be a problem within the gallery component itself?

**Comment by demiankatz** [comment]
Thanks for trying! I asked about `width: auto` because simply disabling the existing `width: 100px` on the slider in the browser inspector makes it get wider, so I thought this might have the same effect. Clearly there's more to it than that!

@Saira-A, I don't think the problem is part of the underlying component, because I don't see this Firefox problem when I run the component directly. I think there's style somewhere that's designed to make the slider smaller than the default size provided by the component, and it's using a technique that doesn't work right in Firefox for whatever reason. I'm not sure exactly where that style lives, though -- I spent a little time yesterday trying to figure it out but didn't have any luck.

**Comment by demiankatz** [comment]
@Saira-A, one other thought: [this StackOverflow about range inputs and z-index](https://stackoverflow.com/questions/30723341/different-z-index-for-thumb-and-track-in-html5-range-slider-in-firefox) demonstrates some Firefox-specific CSS selectors for controlling the range input. I wonder if we can leverage those in some way to fix the problem.

**Comment by LanieOkorodudu** [comment]
> In any case, I'll approve this for now. We should probably get one more thumbs-up (maybe from @LanieOkorodudu?) before we actually merge it. Once that's done, we can go ahead with the follow-up to fix the slider width.

@demiankatz, I just tested it and looks good to me. Thank you both.

**Comment by LanieOkorodudu** [comment]
https://github.com/user-attachments/assets/37a07c41-faa9-4c0b-ab44-c53b5497cc89

I also tested in Firefox. Looks okay though not same on chrome.

**Comment by Saira-A** [comment]
> Universal.Viewer.Examples.Mozilla.Firefox.2024-10-29.10-58-11.mp4 
> I also tested in Firefox. Looks okay though not same on chrome.

I've opened a new PR to address that :)

**Pull request merged**
