### PR TITLE
Update $next and $previous strings (fixes #1087)

### LINKED ISSUE #1087: Accessibility issue: ambiguous accessible label for previous and next button
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
previous and next button inside image controls

### Issue description
These buttons have the title "Previous" and "Next" which is not as descriptive as it should be. A non-sighted user may not be aware that they are in an image viewer. It has never really been announced when the user entered the image viewer by tabbing. They would have to come to this conclusion by observing other buttons (like the zoom in and out buttons) and also conclude that the proximity to the other buttons means that the previous and next buttons also apply to an image. A lot of assumptions.

### Steps to reproduce
1. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
2. use a screenreader to navigate to the previous and next buttons inside the image viewer and observe what is announced

### Expected behaviour
Clear accessible labels that leave no doubt to users of assistive technology what they do.

### Possible fix
change the title attribute to "Next button" and "Previous button"

### WCAG criterion
[4.1.2 Name, Role, Value (Level A)](https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html)

### Related code

```html
<div class="paging btn prev" tabindex="0" title="Previous" style="position: relative; padding-left: 0px; padding-top: 0px; display: inline-block; top: 239px;"></div>
```

### Other information
**Note**: This thinking could reasonably be applied to all the buttons in image controls but since something like zoom is usually assumed to apply to visuals, I have not raised it. It would not be a bad idea to go through the button names and labels and assess if their accessible lables can be improved.

### PR DESCRIPTION
**Pull request by LlGC-mag**
Fixes https://github.com/UniversalViewer/universalviewer/issues/1087

Updated `$next` and `$previous` strings for en-GB, cy-GB, sv-SE, fr-FR, pl-PL

Tested using VoiceOver on MacOS

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
This PR does exactly what #1087 requests, but I'm not sure I agree with the original suggestion. We now have buttons at the top of the panel which are titled "Next Image" and "Previous Image" and which navigate back and forth between images. We also have the floating buttons on top of the image which are titled "Next Button" and "Previous Button" but which do exactly the same thing as the other buttons. I don't understand why we would want to label these differently if they do exactly the same thing. Saying "Next Button" makes me think they'll somehow navigate to a different button instead of navigate to a different image, which doesn't make any sense to me.

Would it be better to use the existing nextImage/previousImage labels for these controls? Or to aria-hide them because they are redundant in a non-visual context?

Obviously, I defer to the accessibility experts in the group if they feel differently -- but I'm just not sure I understand the motivation of the original suggestion.

**Comment by demiankatz** [comment]
@scoutb-cogapp, any thoughts on this one? I understand your original request in principle, but I wonder if the approach here needs a little adjustment in practice. Your input would be valuable!

**Comment by LlGC-jop** [comment]
I agree @demiankatz

'Next button' describes what it is, not what it does, and from what little I've learned in the last couple of weeks using NVDA, a screen reader will first tell the user that it's a button, and then what the label says.

So my vote is for 'Next image' and 'Previous image' on any button that performs those functions.

**Comment by demiankatz** [comment]
Thanks, @LlGC-jop. So I think we should revert the changes made here and instead find where the strings are set for those buttons and adjust them to use the existing $nextImage / $previousImage translations instead of plain $next / $previous. Would you or @LlGC-mag be interested in adjusting this existing PR, or should we close it and start a new one?

**Comment by LlGC-mag** [comment]
I'm going to close this PR and create a new one as the resulting merge is a bit messy

**Comment by demiankatz** [comment]
Thanks, @LlGC-mag, that makes sense to me!

**Pull request closed without merging**
