### PR TITLE
Share textarea

### PR DESCRIPTION
**Pull request by nicolasfranck**

### CODE REVIEW

**Comment by edsilv** [comment]
I think textarea is suitable for the embed code as multi-line text, although the url is a single line and input is probably more suitable for that?

**Comment by nicolasfranck** [comment]
Yes, but an URL can be long, even as long as the embed code. And it should be visible what you're looking at.

Of course the textarea has also its width and height (and so scrollbars), but this can fixed by overriding
this in a local css theme.

This is my opinion, but maybe make this configurable?

**Comment by edsilv** [comment]
Have added to the next community call agenda

**Comment by edsilv** [comment]
Make embed a textarea of one line by default that can be overridden in the theme.

**Pull request closed without merging**
