### PR TITLE
Adding image dropdown to header panel

### PR DESCRIPTION
**Pull request by Edminsson**
I'm not sure you were interested in this feature or we were suppossed to wait with all these kind of changes. Anyway here it is and it's disabled by default.

### CODE REVIEW

**Comment by demiankatz** [comment]
A couple of questions/comments (based on a code read rather than actually executing anything, so apologies if I'm misinterpreting what I see):

1.) Is the code dealing with hiding this.$search and blurring/focusing elements based on tab index directly related to the dropdown behavior? Just wondering if that should actually be a separate pull request for greater clarity.

2.) Should the `<option>` elements be constructed a little differently to avoid the possibility of generating invalid HTML? (i.e. what if you have a page whose label is "`</option>`"?

**Comment by Edminsson** [comment]
1) You are right that the code is dealing with two issues. Firstly, if enabled, a dropdown is created where the options are the label of the canvas. Secondly the code is also handling the keyboard navigation with the TAB key more dynamically.
2) Yes, you could generate invalid HTML and  to prevent XSS the content of the option elements could be escaped.
So valid points indeed.

**Comment by ra-magnus-welander** [comment]
Hey guys, are you still interested in this one? If so, I can try to split it up into two separate pull requests with the XSS flaw fixed. Just tell me!

**Comment by edsilv** [comment]
I think we can go ahead and merge this. I will abstract the elementWithGreatestTabIndex stuff out into this https://github.com/edsilv/jquery-plugins. 

The Bodleian have need of a drop down box instead of text entry:

https://gitter.im/UniversalViewer/universalviewer?at=56658bc9c15bca7e3c967759

We can show them the UV with this enabled and get their feedback.

**Comment by edsilv** [comment]
I made a few changes. 

- The option is renamed to `imageSelectionBoxEnabled` - seems a bit more descriptive of its function.
- `getVisibleElementWithGreatestTabIndex` is now a jquery plugin.
- The search options are hidden if `imageSelectionBoxEnabled` is true.

I've also updated the `dev` branch to be parallel with `master`. I'm thinking that for new features we could use this branch for testing pull requests before they are merged to `master`?

**Comment by ra-magnus-welander** [comment]
Yeah, great, those seem like good changes. So when we issue pull requests we will do them against the dev branch from now on?

**Comment by edsilv** [comment]
Cool. Yep, let's give the dev branch a try for pull requests - this will give us a 'staging' area to test things.

**Pull request merged**
