### PR TITLE
Disable previous button (resolves #888)

### LINKED ISSUE #888: Previous button is accessible via keyboard when it's disabled
**UV version:**
` universalviewer@4.0.9
`
**I'm submitting a:**
`[ x]` bug report

**Current behaviour:**

At the moment, a keyboard user can use the previous button in the header panel even if it's disabled via CSS. When the button is clicked, it will produce an error:

image

The position placemaker will also go off the screen when the previous button is clicked enough times:

image

**Expected behavior:**

The button should be disabled for all users.

**Steps to reproduce:**
Use the tab key to get to the previous button in the header panel, and when the page no is 1 or less, press the enter key. The error will then appear.

**Other information:**

It might be better to use Javascript to disable the button, adding something like below into **PagingHeaderPanel.ts**  would do the trick.

In the **disablePrevButton** method, add:
`this.$prevButton.attr("disabled","disabled");`

and in **enablePrevButtion**, remove the attribute:
 
`this.$prevButton.removeAttr("disabled");`

### PR DESCRIPTION
**Pull request by Saira-A**
#### Description of what you did:

Disable previous button from being accessible via keyboard when on first page #888

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
@Saira-A, if this solves a problem, should we also add parallel behavior to the disableNextButton/enableNextButton methods so everything is consistent?

**Comment by Saira-A** [comment]
> @Saira-A, if this solves a problem, should we also add parallel behavior to the disableNextButton/enableNextButton methods so everything is consistent?

Like this? This causes another issue where the previous button becomes greyed out when on the last page. Otherwise it still has the runtime error that prevbutton had but it just loops back to the first page instead of going into negative numbers
  ```
disableNextButton(): void {
    this.nextButtonEnabled = false;
    this.$nextButton.disable();
    this.$prevButton.attr("disabled","disabled");
  }

  enableNextButton(): void {
    this.nextButtonEnabled = true;
    this.$nextButton.enable();
    this.$prevButton.removeAttr("disabled");
  }
```

**Comment by demiankatz** [comment]
> > @Saira-A, if this solves a problem, should we also add parallel behavior to the disableNextButton/enableNextButton methods so everything is consistent?
> 
> Like this? This causes another issue where the previous button becomes greyed out when on the last page. Otherwise it still has the runtime error that prevbutton had but it just loops back to the first page instead of going into negative numbers
> 
> ```
> disableNextButton(): void {
>   this.nextButtonEnabled = false;
>   this.$nextButton.disable();
>   this.$prevButton.attr("disabled","disabled");
> }
> 
> enableNextButton(): void {
>   this.nextButtonEnabled = true;
>   this.$nextButton.enable();
>   this.$prevButton.removeAttr("disabled");
> }
> ```

@Saira-A, I think you just need to change "$prevButton" to "$nextButton" in that code snippet, so that the next button is disabled instead of the prev button. :-)

**Comment by Saira-A** [comment]
> > > @Saira-A, if this solves a problem, should we also add parallel behavior to the disableNextButton/enableNextButton methods so everything is consistent?
> > 
> > 
> > Like this? This causes another issue where the previous button becomes greyed out when on the last page. Otherwise it still has the runtime error that prevbutton had but it just loops back to the first page instead of going into negative numbers
> > ```
> > disableNextButton(): void {
> >   this.nextButtonEnabled = false;
> >   this.$nextButton.disable();
> >   this.$prevButton.attr("disabled","disabled");
> > }
> > 
> > enableNextButton(): void {
> >   this.nextButtonEnabled = true;
> >   this.$nextButton.enable();
> >   this.$prevButton.removeAttr("disabled");
> > }
> > ```
> 
> @Saira-A, I think you just need to change "$prevButton" to "$nextButton" in that code snippet, so that the next button is disabled instead of the prev button. :-)

Oops, that would explain it! fixed

**Review by demiankatz — APPROVED** [review]
Thanks, @Saira-A! This makes sense to me if @LanieOkorodudu can't find any problems. :-)

**Comment by LanieOkorodudu** [comment]
> Thanks, @Saira-A! This makes sense to me if @LanieOkorodudu can't find any problems. :-)

I think the prev button still not working using the keyboard..

**Review by demiankatz — CHANGES_REQUESTED** [review]
I think I see what @LanieOkorodudu is talking about. I think the prev/next buttons are working now, but there are also first/last buttons that need the same treatment in their functions (just above the ones that have already been adjusted). I think that should fully solve the problem.

**Comment by LanieOkorodudu** [comment]
> > I think the prev button still not working using the keyboard..
> 
> It only works if you click the button first and then use the enter key, it doesn't use the left/right arrow keys if that's what you mean @LanieOkorodudu
> 
> I added the same to the first/last buttons, thanks @demiankatz

@Saira-A Yes that's what I mean but probably that's different issue to address. I just check it in vercel app and it's working now. Just as you said you have to initiate the click first then press enter key. This should address and solve the issue #888. Thanks again @Saira-A and @demiankatz

**Pull request merged**
