### PR TITLE
Keep focus on gallery button when selected

### LINKED ISSUE #1073: Accessibility bug: focus order skips many items when activating icon gallery
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
icon gallery button

### Issue description
Activating the icon gallery with the icon-gallery-button by keyboard moves focus to the more-information-button on the right side of the screen (the little chevrons). This skips whole sections of the page in the tab order: the options button and all the image controls. 

### Steps to reproduce
1. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
2. use keyboard navigation to activate the gallery icon in the top right
3. observe that focus moved to the chevron-button
4. activate that button by pressing spacebar
5. observe that sidebar closes
6. continue tabbing and observe focus moving to download button

### Expected behaviour
Focus remains with the button that activates the gallery view. This way, a user can simply close that view again and continue their journey.

### WCAG criterion
2.4.3 Focus Order (Level A)

### PR DESCRIPTION
**Pull request by Saira-A**
Fixes #1073

### CODE REVIEW

**Review by demiankatz — APPROVED** [review]
Thanks, @Saira-A! I think this is probably a relic from the old days when the gallery control worked differently. This seems well worth doing, but I'll hold off on merging until @LanieOkorodudu has a chance to confirm.

Also, a related issue: I notice that if you do focus the gallery collapse button with the keyboard, you can only activate it with spacebar, but that causes the page to scroll down unexpectedly. We probably need to fix the accessibility of that control. That's a problem for a separate issue/PR; let me know if you'd like me to open an issue to document the situation!

**Comment by Saira-A** [comment]
> Thanks, @Saira-A! I think this is probably a relic from the old days when the gallery control worked differently. This seems well worth doing, but I'll hold off on merging until @LanieOkorodudu has a chance to confirm.
> 
> Also, a related issue: I notice that if you do focus the gallery collapse button with the keyboard, you can only activate it with spacebar, but that causes the page to scroll down unexpectedly. We probably need to fix the accessibility of that control. That's a problem for a separate issue/PR; let me know if you'd like me to open an issue to document the situation!

Thanks @demiankatz! The collapse button issue is mentioned in #1084 and as you said there it's probably best to break it into smaller tasks

**Comment by demiankatz** [comment]
Great, thanks for confirming that the issue is already documented!

**Review by jamesmisson — APPROVED** [review]
Code and preview both look good to me.

**Pull request merged**
