### PR TITLE
Address range highlighting bug (Fixes #955)

### LINKED ISSUE #955: Overlapping ranges make some titles in de index tab not "clickable"
**UV version:**

```
 universalviewer@4.0.25
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below

**Current behavior:**

When I provide a manifest with overlapping ranges (two ranges have one or more of the same canvases),
one of the titles do not react "properly", i.e. when clicked the title does not become
blue and the first canvas is not triggered.

P.S. When navigating through the image list, the right range titles are selected, so that part
works perfectly.

**Expected behavior:**

Overlapping ranges should work

P.S. it works in https://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb19974760-0%2Fmanifest&locale=en-GB#?c=&m=&s=&cv=3&manifest=https%3A%2F%2Fadore.ugent.be%2FIIIF%2Fmanifests%2Frange-test&xywh=0%2C-1599%2C10937%2C10415 which is probably based on an older version

**Steps to reproduce:**

* Use manifest https://adore.ugent.be/IIIF/manifests/range-test in the latest UV. Example: https://www.universalviewer.dev/#?xywh=-396%2C-1%2C11729%2C7219&iiifManifestId=https%3A%2F%2Fadore.ugent.be%2FIIIF%2Fmanifests%2Frange-test&cv=4&rid=https%3A%2F%2Fadore.ugent.be%2FIIIF%2Fmanifests%2Frange-test%2Franges%2Frange-test%253AR.4
* go tab "index"
* click on title "range 4". Nothing happens. The first canvas of that range is the last canvas of the previous range.

### PR DESCRIPTION
**Pull request by nicolasfranck**
Fixes #955

As noted in the issue, I do not know if this breaks other stuff,
i.e. data that is not shown in openseadragon.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @nicolasfranck. I see that selectCurrentTreeNode() contains a 4-year-old TODO comment which implies that the eventual plan was to eliminate the need for two separate select methods entirely... so if that refactoring eventually occurs, your proposed change would need to be undone. But if it's fixing problems in the meantime, it seems relatively harmless, given that it's updating the tree node using the appropriate method for the event that caused the tree node to change initially. However, I see that there are several other calls to selectCurrentTreeNode in other parts of the file, and I'm not sure if these might still have bugs related to ranges. If they do, those bugs might be harder to fix.

In any case, bottom line: it seems unlikely to me that this fix makes things worse or causes new breakages, but I'm not sure if it fixes every problem related to the underlying problem. I'd love input from @edsilv if he has any memory of the context of this, but I'd be reasonably comfortable with approving and merging this fix if you need it resolved before Ed has a chance to respond. Feel free to follow up here if you need further action from my end.

**Comment by alexrostronbl** [comment]
Danny and Alex have started to test this - thanks

**Comment by alexrostronbl** [comment]
Tested using the manifest that was not working when choosing item 4 from the index using this URL: https://universalviewer-git-fork-nicolasfranck-patch-2-mnemoscene.vercel.app/#?xywh=0%2C-86%2C10937%2C7389&cv=4&rid=https%3A%2F%2Fadore.ugent.be%2FIIIF%2Fmanifests%2Frange-test%2Franges%2Frange-test%253AR.4&iiifManifestId=https%3A%2F%2Fadore.ugent.be%2FIIIF%2Fmanifests%2Frange-test

Evidence:

image

**Review by demiankatz — APPROVED** [review]
I'm going to go ahead and approve this given the test evidence presented. I won't hit the merge button until @alexrostronbl confirms that all testing is complete, however. Please let me know!

**Comment by alexrostronbl** [comment]
Hi @demiankatz I can confirm that all testing is complete for this issue so please merge. I don't seem to have rights to do an official approval if this is needed - thanks

**Pull request merged**
