### PR TITLE
Upgrading to Openseadragon v4

### PR DESCRIPTION
**Pull request by 404mike**
Upgrade openseadragon dependancy to version `4.0.0`. Current version `2.4.2` contains `eval` function in production release. Openseadragon has removed this code in its latest release.

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @404mike -- I noticed that build is failing here -- I think the comment below explains why. Let me know if I can do more to help!

**Comment by LlGC-szw** [comment]
@404mike  Could report on progress on this please?

**Comment by demiankatz** [comment]
Thanks, @404mike. Next questions:

1.) I see that there are some newer openseadragon versions available now -- 4.1.1 and 5.0.0 being possible candidates for a next step forward. Do we want to merge this first as an incremental step, or should we try out the newer releases?

2.) Assuming we want to stick with the version that's chosen here, would you like some help testing this? I imagine it would be a good idea to carefully put OSD through its paces to be sure nothing has broken, given the large version jump here.

**Comment by 404mike** [comment]
@demiankatz v4 seems fine. v5 doesn't work quite right. 

It throws an error `OpenSeadragonCenterPanel.ts:420 Error adding handler for tile-drawn. The WebGLDrawer does not raise the tile-drawn event`. The viewer continually displays the spinning icon in the main viewer panel.

**Review by demiankatz — APPROVED** [review]
This looks good to me so far, but I'd appreciate if @LanieOkorodudu or others could also take a look!

**Comment by demiankatz** [comment]
I've also gone ahead and bumped this to 4.1.1 so we're on the latest 4.x release; it seems to work just as well as 4.0.0.

**Comment by LanieOkorodudu** [comment]
> This looks good to me so far, but I'd appreciate if @LanieOkorodudu or others could also take a look!

Looks good for me too @demiankatz

**Comment by 404mike** [comment]
Thank you @demiankatz @jenlindner

**Comment by demiankatz** [comment]
Thanks, everyone -- merging now!

**Pull request merged**
