### PR TITLE
Download improvements

### PR DESCRIPTION
**Pull request by demiankatz**
There's a lot going on in this PR, so I left it as three separate commits to aid readability. This is the biggest refactoring I've attempted thus far, so apologies if I've moved anything in the wrong direction.

Here's a summary of all the changes:

- Created a base DownloadDialogue class to store common functionality shared between the DownloadDialog classes in all of the extensions.
- Merged together all of the DownloadOptions classes into a single Class (I don't think there's any harm in effectively sharing the same constants between the extensions).
- Adjusted the MediaElement download dialog box to use labels and mime types instead of a hard-coded text string and file extensions (though it fails over to the old way if data is missing).
- Adjusted the PDF download dialog box to mirror the behavior of MediaElement (the old logic looked for a media element on the canvas, and I think that's legacy behavior).

Hopefully this is all a step in the right direction, but please let me know if further adjustments are needed.

Also note that we're now focusing entirely on renderings for MediaElement and PDF. I've found that to get the current code to work right, I need to include the same URL both as the `@id` of the element in the manifest AND as an entry in the renderings. I'm not sure if this is desired/intended behavior, and it's possible that we may need to add more smarts to account for different variations of the manifest. Let me know if you need examples and I can experiment with this more extensively.

### CODE REVIEW

**Comment by edsilv** [comment]
Ok, looks good. It might make more sense for DownloadOption.ts to go in uv-shared-module.

**Comment by demiankatz** [comment]
I certainly have no objection to moving DownloadOptions -- and I can do the work if you want me to. Just let me know!

**Comment by edsilv** [comment]
Great, if you wouldn't mind I think that would fit more with the current
conventions.

**Comment by demiankatz** [comment]
Sure, I'll take care of that in the near future.

**Comment by tomcrane** [comment]
http://wellcomelibrary.org/item/b20234272 

Download dialogue thinks the UV is in 2-up mode

**Comment by demiankatz** [comment]
I'm able to reproduce the problem using a clean build of the UV, so it's not something specific to the Wellcome Library configuration. I notice that this item is not displaying the option to switch between one-page and two-page views, so it seems that something about the manifest or images is confusing the viewer. I'm willing to look into this further if you want me to, but I'll wait and see what @edsilv has to say first. I don't think this is directly related to the changes to the download code but is rather a side effect of something happening at a higher level that I'm less familiar with -- but I'm certainly willing to learn and explore when time permits.

**Comment by edsilv** [comment]
Just pushed a fix for this.

**Pull request merged**
