### PR TITLE
Update aleph-r3f branch

### PR DESCRIPTION
**Pull request by JulieWinchester**
This PR updates the aleph-r3f branch to include latest main branch code and fixes bugs and improves functionality when using the AlephR3F or legacy Aleph extensions for viewing 3D content. Specifically it:
* Merges latest main branch commits
* Creates a new extension, `ALEPHLEGACY`, which maps to the `uv-aleph-extension` that supports use of the legacy Aleph viewer (https://github.com/aleph-viewer/aleph) in UV. The extension `ALEPH` continues to map to `uv-aleph-r3f-extension` supporting the newer Aleph-R3F viewer (https://github.com/aleph-viewer/aleph-r3f). This is necessary in order to view CT or other volumetric 3D content in UV. 
* Updates version of legacy Aleph to 0.0.21. 
* Updates Aleph-R3F to use latest github commit. This should be modified to use an npm release of Aleph-r3f when one is ready.
* Aleph-R3F left panel is now closed by default on loading content. Also adds a title, "CONTROLS," to the left panel.
* Fixes Aleph-R3F theme styling (was not previously loading) and modifies styling to use Aleph-R3F style background colors.
* Adds attribution positioning to Aleph-R3F. 
* For legacy Aleph, ensures title is displayed on center panel.

### CODE REVIEW

**Comment by JulieWinchester** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Comments	Updated (UTC)
> **universalviewer**	❌ Failed ([Inspect](https://vercel.com/bl-uv-team/universalviewer/5Up2SCqx9hJN1Wq3FYKCTNusti4i))			Nov 7, 2024 5:14pm

I'll be happy to fix whatever is causing this, but when I click the link I get a 404. Maybe I lack access?

**Comment by demiankatz** [comment]
@JulieWinchester, I've found that sometimes the Vercel build fails, and then succeeds within about five minutes. In this case, it seems to be stuck for longer. I think @LanieOkorodudu may be able to help find the logs showing what went wrong.

**Comment by LanieOkorodudu** [comment]
@JulieWinchester, and @demiankatz, please see the build log report in the screenshot below.
Screenshot 2024-11-08 103531

**Comment by LanieOkorodudu** [comment]
@JulieWinchester, Below are the attached results from yesterday's deployment. 
Screenshot 2024-11-13 092418

**Pull request closed without merging**
