### PR TITLE
Update iiif-metadata-component to v1.2.0.

### PR DESCRIPTION
**Pull request by demiankatz**
This PR upgrades the iiif-metadata-component to the latest release. This should address several issues: #973, #1081, #1085

### CODE REVIEW

**Comment by jamesmisson** [comment]
Thanks @demiankatz . I am getting an error when trying to load a v3 manifest without a logo property, which goes back to Manifold, so I'll try to work it out this week.

https://collections.library.yale.edu/manifests/16371215

**Comment by jamesmisson** [comment]
Thanks @demiankatz . It was in fact in Manifesto, so I've made a PR over there: https://github.com/IIIF-Commons/manifesto/pull/144

While testing this I also noticed some other odd behaviour with the manifest linked below (empty and duplicate metadata items being added to the metadata component) which I'll investigate tomorrow.

https://bl.digirati.io/iiif/ark:/81055/vdc_100056056799.0x000001

**Comment by demiankatz** [comment]
Okay, I've merged your PR; please let me know if it turns out that another one is needed and/or when you're ready for me to make the next release!

**Review by LanieOkorodudu — COMMENTED** [review]
@demiankatz and @jamesmisson 
#973
- I tested this fix and compared it to the raised issue where three attributes were not added to the right panel.
- Using the manifest, https://adore.ugent.be/IIIF/manifests/arxiv. I confirm that the three attributes have been added when testing on Vercel.

#1081 
-The issue raised here was about adding "descriptive labels along the lines."
- Under "title", "citation", "description", and "attribution" longer text is revealed when expanding the fields.
- However, when testing with NVDA, I observed that:
   1. the screen reader announces only "more or "less" when interacting with these fields. It does not specify if the action pertains to "more information on the title" or "less information on the title."
   2. The same issues applies to other expandable/collapsible fields like "citation", "description", and "attribution."
   3. Currently, the behaviour matches the description in the issue, and I did not notice any changes or improvements.

#1085 
- I tested this issue where several items were being announced as "clickable" on the dev branch where the original issue was raised.
- Comparing this fix to the Vercel app with the fix applied
  - Initially, NVDA announces "clickable" for the first button clicked, but it no longer announces after the first interaction.
  - The behaviour seems fine and resolves the raised concern.

**Comment by demiankatz** [comment]
@jamesmisson, is it possible that #1081 simply hasn't been addressed yet? Or is there some bug we need to investigate further?

@LanieOkorodudu, would you be in favor of merging this PR and closing #973 and #1085 since those two issues are fixed and #1081 is not made worse even though it is not fixed? That would allow us to make some incremental progress... and whatever happens, I expect we'll need a new release of iiif-metadata-component and a separate PR to finish resolving #1081.

**Comment by LanieOkorodudu** [comment]
> @jamesmisson, is it possible that #1081 simply hasn't been addressed yet? Or is there some bug we need to investigate further?
> 
> @LanieOkorodudu, would you be in favor of merging this PR and closing #973 and #1085 since those two issues are fixed and #1081 is not made worse even though it is not fixed? That would allow us to make some incremental progress... and whatever happens, I expect we'll need a new release of iiif-metadata-component and a separate PR to finish resolving #1081.

@demiankatz,  I don’t mind merging this PR and will close the addressed issues. Thanks to both of you for your efforts!"

**Comment by LanieOkorodudu** [comment]
@demiankatz.  Sorry merge pull request icon is greyed out on my side.

**Comment by demiankatz** [comment]
@LanieOkorodudu, the pull request can't be merged until somebody approves it. You should have the power to do this through the review control on the Files tab.

**Review by LanieOkorodudu — APPROVED** [review]
try merging now

**Comment by LanieOkorodudu** [comment]
@jamesmisson , if you think it has address the issue then you can close 1081 then.

**Pull request merged**
