### PR TITLE
Correct minor regression from #1158; add tabindex for consistency.

### LINKED ISSUE #1076: Accessibility issue: image controls disappear when activated by keyboard
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
image controls

### Issue description
The image controls only become visible when a user hovers over the image viewer or when focus is otherwise inside the image viewer. This works well for keyboard users on first navigating the image viewer: buttons remain visible while navigating and they receive a focus frame when accessed by keyboard. Problems arise when the user activates any of the following buttons: zoom in, zoom out, forward, backward. Now, behaviour changes: The interface no longer realises that focus is on the image viewer and all the buttons become invisible. They reappear only under the following circumstances: when the user tabs and by doind so accesses any of the following buttons: zoom in, zoom out, rotate. When any of those is accessed by tabbing, all the buttons reappear. But as soon as the user tabs to the forward or backward button, they disappear again. 

Note that the issue is only about visibility of the buttons, not functionality. The buttons continue to function and can be activated (as long as you count correctly to keep track where focus resides). 

### Steps to reproduce
1. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
2. ensure mouse is not hovering over image viewer
3. tab to the zoom in button
4. activate it
5. observe all the buttons disappear
6. continue tabbing and observe that image controls only remain visible while focus is on zoom or rotate buttons

### Expected behaviour
As long as focus is on any of the image controls (zoom in, zoom out, rotate, forward, backward), all the controls remain visible.

### WCAG criterion
2.4.7 Focus Visible (Level AA)

### Related code

```html
<div class="paging btn prev" tabindex="0" title="Previous" style="position: relative; padding-left: 0px; padding-top: 0px; display: inline-block; top: 327px;"></div>
```

### PR DESCRIPTION
**Pull request by rNegi-bl**
Follow-up to #1158.

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @rNegi-bl, this looks like progress, but it's unfortunately still not quite working for me all the time.

Here's something I'm seeing in Firefox:

1.) I go to the preview and hit tab until I focus the image adjustment button. The button remains focused and visible -- this is what I expect.

2.) Now I hit shift-tab until I focus away from the image controls, so the image controls disappear.

3.) After this point, if I tab forward to the image adjustment control again, the image controls disappear even though the control is focused.

So it seems like some state is getting lost over time after multiple interactions. Can you investigate? Please let me know if you need more help!

**Comment by demiankatz** [comment]
> Hi Damien, I am struggling to recreate the Firefox issue. I am on Windows and Firefox 131.0.3 (64-bit). What's your system and browser?

I have an identical system: Windows 11 + the same 64-bit Firefox 131.0.3.

I also reproduced the same behavior using the same sequence of actions in Chrome 130.0.6723.59 (64-bit), so the problem doesn't seem to be browser-specific.

In case it makes a difference, here's my exact series of keypresses to trigger the condition:

Hit tab 15 times, wait (image doesn't fade), hit shift-tab 5 times, hit tab 5 times, wait (image does fade).

**Comment by rNegi-bl** [comment]
Hi Damien, controlsFadeDelay & controlsFadeLength set for the viewer is fading out the controls. If I give max values to those properties it will keep it visible & they won't fade out. Will that be correct ?

**Comment by demiankatz** [comment]
> Hi Damien, controlsFadeDelay & controlsFadeLength set for the viewer is fading out the controls. If I give max values to those properties it will keep AdjustImageButton visible & they won't fade out. Will that be correct ?

I think the question (which I don't know the answer to) is why this is only a problem for the image adjust button and not the others. Is it possible there is logic attached to those other buttons but not to this one, and things need to be made more consistent?

Your proposed solution may be the best way forward -- I'd just like to be sure we don't treat this button differently from the rest if we don't have to. :-)

Let me know if you need more help researching this; I can take a longer look at the code later today if necessary.

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks for the progress, @rNegi-bl -- I think there's a new issue now, though: once you have focused the adjust controls, then the fade is disabled forever. I think we need to remember the previous values and restore them on blur.

**Review by demiankatz — APPROVED** [review]
Some overlapping work in #1174 has addressed the adjust image button issue in a way that addresses my comments here, so I have reverted the focus handler from this PR so that we can merge the other parts of the work here that correct other issues. I think we can rely on #1174 to fix the remainder of the issue.

**Comment by rNegi-bl** [comment]
Hi Demian, this merge will close #1076 ?

**Pull request merged**
