### PR TITLE
Added option to save user settings to localStorage.

### PR DESCRIPTION
**Pull request by bazer**
Hi again!

I used your new code for saving to localStorage to implement saving of the options in the settings dialog. It saves the setting for navigator, paging and viewport, but not the language. I set it to save for 10 years, don't know if that's a good idea or not.

### CODE REVIEW

**Comment by edsilv** [comment]
Nice. I think I'd change the storage key from "settings" to something more specific like "uv.settings" as it's going into local, not session storage.

**Comment by bazer** [comment]
Isn't the local storage unique per domain anyway? But yeah, it should probably be a bit more specific, uv.settings sounds good.

I can change it and append the pull request, but I'm not back in the office until Monday so it'll have to wait until then. Or just merge and change it if you want the patch now.

**Comment by edsilv** [comment]
let's stick with 'settings'.

**Comment by edsilv** [comment]
I went with "uv.settings" in the end. The UV may share storage with other apps on the domain - better to namespace it I think.

**Comment by bazer** [comment]
Great! I'll merge it back into our code.

**Pull request merged**
