### PR TITLE
Copy right panel data to clipboard

### PR DESCRIPTION
**Pull request by ra-magnus-welander**
Button shows on hover over the element for mouse devices and always shows on touch devices. A small confirm message shows once the button is pushed.

### CODE REVIEW

**Comment by edsilv** [comment]
Hi, it looks like you've directly edited /lib/utils.js - This is a bower component from here: https://github.com/edsilv/utils

Would it be possible to add a pull request for the utils library?

**Comment by ra-magnus-welander** [comment]
I did. Check out edsilv/utils!

/Magnus

>>> Edward Silverton <notifications@github.com> 2016-03-17 17:50 >>>

Hi, it looks like you've directly edited /lib/utils.js - This is a bower component from here: https://github.com/edsilv/utils
Would it be possible to add a pull request for the utils library?

**Comment by edsilv** [comment]
Woops! I've merged that to utils. Just thinking, would it make sense to move IsTouch from the Panel base class to Utils.Documents?

Also, I might be missing it - but it looks like copy to clipboard is enabled by default? After talking to Jenn at Wellcome I think it might be better if this were a feature that libraries could _enable_, rather than it being the default?

**Comment by jennpb** [comment]
Yes, please make it possible to disable Copy to Clipboard. This isn't something that we require, and thus adds more complexity to the UV than we wish to offer.

**Comment by ra-magnus-welander** [comment]
Yes, of course, IsTouch makes more sense in Utils, and I'll add the config to enable/disable the copy-function (disabled by default).

**Comment by ra-magnus-welander** [comment]
Committed the requested changes, I hope everything is fine now. I don't think that I'm causing the tests to fail, but if I'm to blame, please let me know.

**Comment by edsilv** [comment]
Looks good. Sometimes Travis chokes randomly - running the test again usually solves it.

**Pull request merged**
