### PR TITLE
Improve screen reader representation of OSD buttons (fixes #1170)

### LINKED ISSUE #1076: Accessibility issue: image controls disappear when activated by keyboard
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
image controls

### Issue description
The image controls only become visible when a user hovers over the image viewer or when focus is otherwise inside the image viewer. This works well for keyboard users on first navigating the image viewer: buttons remain visible while navigating and they receive a focus frame when accessed by keyboard. Problems arise when the user activates any of the following buttons: zoom in, zoom out, forward, backward. Now, behaviour changes: The interface no longer realises that focus is on the image viewer and all the buttons become invisible. They reappear only under the following circumstances: when the user tabs and by doind so accesses any of the following buttons: zoom in, zoom out, rotate. When any of those is accessed by tabbing, all the buttons reappear. But as soon as the user tabs to the forward or backward button, they disappear again. 

Note that the issue is only about visibility of the buttons, not functionality. The buttons continue to function and can be activated (as long as you count correctly to keep track where focus resides). 

### Steps to reproduce
1. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
2. ensure mouse is not hovering over image viewer
3. tab to the zoom in button
4. activate it
5. observe all the buttons disappear
6. continue tabbing and observe that image controls only remain visible while focus is on zoom or rotate buttons

### Expected behaviour
As long as focus is on any of the image controls (zoom in, zoom out, rotate, forward, backward), all the controls remain visible.

### WCAG criterion
2.4.7 Focus Visible (Level AA)

### Related code

```html
<div class="paging btn prev" tabindex="0" title="Previous" style="position: relative; padding-left: 0px; padding-top: 0px; display: inline-block; top: 327px;"></div>
```

### LINKED ISSUE #1170: Screen reader describes OSD controls as clickable divs
UV version: universalviewer@4.0.25

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

This issue has been split out from here: https://github.com/UniversalViewer/universalviewer/issues/1085
When using a screen reader, the OpenSeaDragon controls (zoom, rotate, and the image adjustment and home buttons currently in dev) are described as 'zoom clickable', and should be just 'zoom'. It would be better for accessibility to have them as button elements.
See this comment: https://github.com/UniversalViewer/universalviewer/issues/1085#issuecomment-2413948841

**Expected behavior:**

Screen readers describe them as buttons with their title.

**Steps to reproduce:**

1. activate NVDA screenreader (requires Windows)
2. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
3. use the keyboard to navigate to the items mentioned and observe how they are announced by the screenreader.

**Other information:**

These buttons are generated by OSD and div is the default element. It's possible to define which element they are generated as via the Button class. See OSD docs here: https://openseadragon.github.io/docs/OpenSeadragon.Button.html

### PR DESCRIPTION
**Pull request by LlGC-jop**
It's not ideal, but this will copy the old 'buttons' into proper button elements and give them the right click handler, which should work for space + enter as well due to the element type.

Fixes #1076 and #1170.

### CODE REVIEW

**Review by demiankatz — APPROVED** [review]
I agree that this isn't especially pretty, but I can't think of a better way, and it works very nicely. Thanks, @LlGC-jop!

**Comment by LlGC-jop** [comment]
@demiankatz The mobile footer has a separate set of buttons outside of the main panel, which I assume use IIIF events to trigger the actions in OSD.

At some point when we want to do an overhaul of things re styling and responsiveness we can look at making this a single element shared between mobile + desktop so the OSD controls aren't used at all.

**Comment by demiankatz** [comment]
> @demiankatz The mobile footer has a separate set of buttons outside of the main panel, which I assume use IIIF events to trigger the actions in OSD.
> 
> At some point when we want to do an overhaul of things re styling and responsiveness we can look at making this a single element shared between mobile + desktop so the OSD controls aren't used at all.

Yes, that's a good point. We also have the "image adjust" button which is a locally-created button that's appended on to the OSD-created buttons. Just building everything consistently is probably less confusing in the long run!

**Review by demiankatz — CHANGES_REQUESTED** [review]
I noticed there were some conflicts here, so I went ahead and resolved them. While testing the results, I noticed that the controls do not appear as expected when they are activated by tabbing with the keyboard. I wonder if we need to apply the solution-in-progress from #1168 to the newly generated buttons here, once it is finalized; I suspect that rebuilding the buttons is causing some internal OSD listeners to get lost.

**Comment by LlGC-jop** [comment]
I think I see what you mean @demiankatz, the controls don't get focus when tabbing forwards, but when you go backwards they do. 

Looks like they've got tabindex=0 which should explain that I think. I'll try removing it.

Re the listeners, they should be the same ones that the mobile versions of the buttons have, so there shouldn't be anything missing.

Either way, I'll fix the tabbing issue and let you know when it can be re-tested.

**Comment by LlGC-jop** [comment]
I've added listeners for focus and blur to the controls to make sure they show up when appropriate.

Again, not the most elegant solution, but it works well enough without needing to dig around in OSD.

I also found that the prev/next buttons didn't have a blur handler so I've added that as well.

All seems to work ok now, both with and without the reduced animation setting.

**Review by demiankatz — APPROVED** [review]
Thanks, @LlGC-jop, this all looks good to me now. Your work here also solves #1076, which still had some ongoing work in progress in #1158. Since #1158 included multiple fixes, I reverted the parts of it that would conflict with this PR and merged the rest, then merged the dev branch back into this PR. After all that, everything still seems to be working as expected/desired.

I'd appreciate it if somebody else could test for good measure, but once we get thumbs-up from one more person, I'm comfortable merging this one!

**Review by LanieOkorodudu — COMMENTED** [review]
@LlGC-jop @demiankatz, I’ve tested the fixes, and I can confirm that tabbing, zoom, and the other buttons mentioned in issue #1076 are all functioning as expected. I also tested with the NVDA screen reader, and everything appears accessible and smooth. Great work on this update. Thanks @LlGC-jop

**Pull request merged**
