### PR TITLE
Make hidden skip link visible on focus (fixes #1088)

### LINKED ISSUE #1088: Accessibility issue: invisible skip link
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
"skip to downloads" link at top of page

### Issue description
There is a link on top of the page enabling users to skip to the downloads and alternative formats section at the bottom of the image viewer. When this link is accessed by keyboard it remains invisible. A keyboard user won't know where focus has moved.

### Steps to reproduce
1. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
2. tab to the first item in the tab order (first item button), then tab backwards
3. observe that no link has become visible and no focus highlight is applied to any element

### Expected behaviour
The link becomes visible and receives focus when it is accessed by keyboard

### WCAG criterion
[2.4.7 Focus Visible (Level AA)](https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html)

### Related code

```html
<a class="sr-only" href="#download-btn">Skip to downloads and alternative formats</a>
```

### PR DESCRIPTION
**Pull request by demiankatz**
This fixes #1088.

### CODE REVIEW

**Comment by LanieOkorodudu** [comment]
@demiankatz, I just tested this on the Vercel app. It looks good. Thanks for the fix!

**Comment by demiankatz** [comment]
Thanks for the testing, @LanieOkorodudu! I'll merge this once I also get a thumbs-up from somebody on the code itself.

**Comment by crhallberg** [comment]
This looks good. A more global way would be to add `.sr-only:hover, .sr-only:focus-visible` styles to the CSS (similar to these styles). It looks like there are [opposing styles in the LESS already](https://github.com/UniversalViewer/universalviewer/blob/main/src/content-handlers/iiif/modules/uv-shared-module/css/scaffolding.less#L139) that we can add these selectors to.

**Comment by crhallberg** [comment]
I also found this modern alternative [from the A11y Project](https://www.a11yproject.com/posts/how-to-hide-content/).

```css
.sr-only:not(:focus-visible):not(:active) {
    /* ... */
}
```

**Comment by demiankatz** [comment]
@crhallberg, I tried revising the `.sr-only {` definition to `.sr-only:not(:focus-visible, :active) {` in [scaffolding.less](https://github.com/UniversalViewer/universalviewer/blob/main/src/content-handlers/iiif/modules/uv-shared-module/css/scaffolding.less#L128-L138) instead of my jQuery-based fix. Unfortunately, it doesn't work -- the text remains invisible when focused. Am I misunderstanding your suggestion?

**Review by crhallberg — APPROVED** [review]

**Pull request merged**
