### PR TITLE
Image specific information in the right panel

### PR DESCRIPTION
**Pull request by bazer**
Hi!

This is the pull request for issue #188. This picks up any metadata values defined inside of canvases in the manifest. It works pretty much the same as when defining global metadata values, but it places the values in a new section at the bottom of the right panel. 

The text of the headers can both be configured and does not show if they are empty. A section does not show if there is no metadata for it in the manifest.

The configuration "aggregateValues" combines values from manifest level metadata and canvas level metadata. It takes a comma separated list that should match the value of the label in the metadata. If it finds a match in the canvas metadata, the matching values are aggregated.

For example we declare most of the source reference information only once in the manifest and then append the canvas specific data to the end. Our configuration looks like this:
"aggregateValues": "källhänvisning, source reference"

`"label": [
        {
          "@value": "Källhänvisning",
          "@language": "sv"
        },
        {
          "@value": "Source reference",
          "@language": "en-GB"
        }
      ]`
https://iiif.riksarkivet.se/arkis!C0000263/manifest

It the combines the values from the top of the manifest:
`"value": [
        {
          "@value": "Ervalla kyrkoarkiv, Husförhörslängder, SE/ULA/10219/A I/2 (1751-1763)",
          "@language": "sv"
        },
        {
          "@value": "Ervalla kyrkoarkiv, Husförhörslängder, SE/ULA/10219/A I/2 (1751-1763)",
          "@language": "en-GB"
        }
      ]`

with the values from the canvas:
`"value": [
                {
                  "@value": ", bildid: C0000263_00001",
                  "@language": "sv"
                },
                {
                  "@value": ", bildid: C0000263_00001",
                  "@language": "en-GB"
                }
              ]`

This is running in production on our end, I hope it can be useful for you too.

### CODE REVIEW

**Comment by edsilv** [comment]
looks great! have you tested re-ordering the metadata, license, logo etc using the moreInfoRightPanel `displayOrder` and `exclude` config options?

**Comment by bazer** [comment]
We currently don't have any of the other values except metadata, so I hadn't tested it before. But I tested adding them now and almost everything seems to work as expected. All the values are put in the manifest section where they should be and the ordering and exclusions seems to work too. 

The one thing that doesn't work is if you add metadata to the exclude list, the canvas level metadata is still being displayed. Should I make a new pull request to fix that?

**Comment by edsilv** [comment]
Would it be possible to make the manifest and canvas level metadata independently orderable/excludable?

**Comment by bazer** [comment]
I think so, we could add a new option named something like `excludeFromCanvas`?

Since metadata is the only value being displayed on the canvas level, ordering doesn't really apply. Are the other values, i.e. `license, logo, description and attribution` valid values on the canvas level?

**Comment by edsilv** [comment]
license, logo, description, and attribution can be on a canvas too: http://iiif.io/api/presentation/2.1/#b-summary-of-metadata-requirements

Perhaps we should have manifestDisplayOrder, manifestExclude, canvasDisplayOrder, canvasExclude config options?

**Comment by bazer** [comment]
Sounds like a good idea. At the moment the canvas only reads the metadata, it would have to run all your new code for the other values too, but that shouldn't be too much work to get working.

We have a planning meeting on Monday, I'll see how we prioritize this.

**Comment by tomcrane** [comment]
(from community call) - when there are no canvases with metadata, the "About this book" heading still appears. This should probably not be shown if there is no other metadata.

**Comment by tomcrane** [comment]
@edsilv just a mention as this is a closed PR

**Comment by bazer** [comment]
Good point, I made a PR to hide the manifest header if there is no canvas metadata.

There doesn't seem to be any support in manifesto for reading `license`, `logo`, `description` and `attribution` from canvas, only `metadata`. Maybe we should wait a bit with implementing this until someone wants it and there is a use case? 

I'll make a new PR with `manifestDisplayOrder`, `manifestExclude`, `canvasDisplayOrder` and `canvasExclude `.

**Comment by bazer** [comment]
I made a new PR #255 where you can choose to exclude the canvas metadata. Since canvas can only have one value right now it didn't seem necessary to implement a display order for it. But it should be easy to do if someone wants it.

**Pull request merged**
