### PR TITLE
use manifold that derives authAPIVersion from image service

### PR DESCRIPTION
**Pull request by nicolasfranck**
Requires https://github.com/IIIF-Commons/manifold/pull/2 to work.
I noticed some indirect dependency on a different manifold version in iiif-gallery-component?

### CODE REVIEW

**Comment by nicolasfranck** [comment]
Ok, the pull request in manifold is merged:

https://github.com/IIIF-Commons/manifold/pull/2

Is there any work yet required here?

**Comment by edsilv** [comment]
I've added this to the next community call agenda as it feels like a fairly significant change.  I may need to add merging this to my next "Open Collective day" to ensure everything works correctly. Breaking auth would be highly undesirable for Stanford right now :-)

**Comment by edsilv** [comment]
I'm about to start work on https://github.com/sul-dlss/universalviewer/issues/33
I think once that's done I can look at this.

**Comment by nicolasfranck** [comment]
But you're using that latest version of Manifesto already in this master branch..
which means that Manifesto is deriving the authAPIVersion from the info.json,
but the UV doesn't. So the UV thinks it's version 1.0, while Manifesto detects version
0.9. Ok, nothing strange happens if the info.json declares auth api version 1.0, because
the UV defaults to that same version.

Maybe revert back for now to an older version of Manifesto until you've decided if this works?

**Comment by edsilv** [comment]
Note to self, remove global auth config option

**Comment by edsilv** [comment]
Hi @nicolasfranck 
I've been investigating this more closely today, and think I'm going to roll manifold back for now.
The UV's request pipeline is currently designed in such a way that it needs to know which version of auth to use before requesting a resource. My main concern when implementing auth1 was that there was an option for those using auth0.9 to continue using it via a config option, as the changes were significant enough to make merging the two prohibitively difficult.
I realise this is suboptimal, and when it is time to update auth to the next version after v1 I will try to do so in such a way that auth1 can continue to be supported without configuration.
@irv successfully upgraded an auth0.9 server to auth1 - pehaps he could shed some light on the difficulties involved in that process?

**Comment by edsilv** [comment]
Some context: https://github.com/IIIF/api/issues/795

**Comment by nicolasfranck** [comment]
Indeed.

The main problem is that both the UV and the image api need to be upgraded at the same time if I want to upgrade to this version ( I still have a year old version of the UV )
Also, after the upgrade, the config and/or the info.json can be stuck in cache somewhere, and you
do not know when both use the same  version of the authentication api.

**Comment by irv** [comment]
i still use the 0.9 context for the same reason, and i'll switch them to 1.0 when we move to UV3. but there's no real functional difference between 0.9.3(or maybe 4, i can't remember) and 1.0

**Comment by nicolasfranck** [comment]
@irv indeed there is no functional difference between both authentication api's, but the manifold code thinks like this:

* auth01: start looking for the other auth01 services (login, logout, token)
* auth09: start looking for the other auth09 services (login, logout, token)

So both manifold/UV and the image api must align now.

**Pull request closed without merging**
