### PR TITLE
Add attribution close label (fixes #1075)

### LINKED ISSUE #1075: Accessibility issue: insufficient label on attribution box close button
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
close button for attribution box

### Issue description
The accessible label for the close button for the attribution box is "close". It is hard for a screenreader user to assess what this button is meant to close. 
Even having the text above and below the button read out by the screenreader will not make it 100 percent obvious what the button closes (especially as the button appears to be positioned between the heading of the box and its content).

### Steps to reproduce
To observe what a screenreader user experiences:
1. activate a screenreader
2. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
3. navigate to the attribution box by tabbing and listen to what is announced
4. attempt to find out more about the close button by further navigating using the keyboard and screenreader

### Expected behaviour
Button should be announced in a way that a non-sighted user would understand its context and purpose.

### Possible fix
Change accessible label to something along the lines of "close attribution box"

### WCAG criterion
2.4.4 Link Purpose (In Context) (Level A)

### Related code

```html
<button type="button" class="close" aria-label="Close"> <span aria-hidden="true">×</span> </button>
```

### PR DESCRIPTION
**Pull request by LlGC-mag**
Fixes #1075 

Added `$closeAttribution` string and added to all extensions.
Translations added: en-GB, cy-GB, sv-SE
Additional translations required: fr-FR, pl-PL

Tested using VoiceOver on MacOS with the following manifests:
https://eap.bl.uk/archive-file/EAP500-1-1/manifest
https://damsssl.llgc.org.uk/iiif/2.0/2373813/manifest.json
http://dams.llgc.org.uk/iiif/2.0/4389767/manifest.json
http://dams.llgc.org.uk/iiif/2.0/1123257/manifest.json
http://dams.llgc.org.uk/iiif/archive/3975658/fonds.json
http://iiif.bodleian.ox.ac.uk/iiif/manifest/60834383-7146-41ab-bfe1-48ee97bc04be.json
https://digital.library.villanova.edu/Item/vudl:24299/Manifest
https://digital.library.villanova.edu/Collection/vudl:3/IIIF
https://digital.library.villanova.edu/Item/vudl:60609/Manifest
https://digital.library.villanova.edu/Item/vudl:30471/Manifest
https://edsilv.github.io/test-manifests/non-paged.json
https://edsilv.github.io/test-manifests/download-service-enabled.json
https://edsilv.github.io/test-manifests/download-service-disabled.json
https://d.lib.ncsu.edu/collections/catalog/nubian-message-2003-04-01/manifest?v3=true
https://purl.stanford.edu/bh502xm3351/iiif3/manifest
https://biiif-template-example-3kntb3jpl-mnemoscene.vercel.app/audio/index.json
https://biiif-template-example-3kntb3jpl-mnemoscene.vercel.app/pdf/index.json
https://biiif-template-zine.vercel.app/index.json

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @LlGC-mag, makes sense to me! I'll be happy to approve once the translations come in.

**Comment by LlGC-mag** [comment]
Morning @demiankatz . Just noticed vercel is saying this failed but it was working fine when I first pushed it up. Translations added now so it's ready to go when I move it from draft

**Comment by demiankatz** [comment]
> Morning @demiankatz . Just noticed vercel is saying this failed but it was working fine when I first pushed it up. Translations added now so it's ready to go when I move it from draft

Vercel sometimes says it's failing for a period of time while things are processing, and then it sorts itself out. That seems to be what happened here, since I see that the preview is fine now.

**Review by demiankatz — CHANGES_REQUESTED** [review]
One suggestion before we merge this: while this solution works, it feels to me a little inconsistent now that I look at it more closely. I think there are two possible ways we could reduce the inconsistency; I'll let you decide which one is better (or, feel free to disagree if you think it's a waste of time to do either).

Option 1: Rather than mapping $closeAttribution to "close", would it be better to create a separate "closeAttribution" value in the type and configuration, and then use that in the code instead? This approach might be preferable if we anticipate the possibility of the situation where there's a visible on-screen "close" text that can be short due to the visual context, but we need a longer accessible text to differentiate for screen readers. If you don't think anyone would ever want that, then this approach is probably more work than it's worth.

Option 2: I notice that you have only changed the "close" text for the extension-specific configurations... however, each config.json section also includes a generic section for the base center panel. This generic section gets overridden, so it's not technically necessary to change it... but I could imagine a future where we refactor the configurations to be less redundant, and should that happen, it might be a good idea for the base panel configurations to match the extended panel configurations, so we don't get confused or lose this behavior.

Sorry to nitpick, but since this is a slight diversion from the usual pattern, I just want to be sure we do things as clearly as we can. What do you think?

**Pull request closed without merging**
